export default function ApprovalTimeline({ approvals = [] }) {
      const statusColor = (s) => s === 'approved' ? '#00C37B' : s === 'rejected' ? '#E84545' : '#1E2D45';
        const statusIcon  = (s) => s === 'approved' ? '✓' : s === 'rejected' ? '✗' : '○';

          return (
              <div>
                    {approvals.map((ap, i) => {
                            const isActive = ap.status === 'pending' &&
                                      (i === 0 || approvals[i - 1]?.status === 'approved');
                                              return (
                                                        <div key={i} style={{ display: 'flex', gap: 12, marginBottom: 4 }}>
                                                                    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                                                                                  <div style={{
                                                                                                  width:          34,
                                                                                                                  height:         34,
                                                                                                                                  borderRadius:   '50%',
                                                                                                                                                  border:         `2px solid ${statusColor(ap.status)}`,
                                                                                                                                                                  display:        'flex',
                                                                                                                                                                                  alignItems:     'center',
                                                                                                                                                                                                  justifyContent: 'center',
                                                                                                                                                                                                                  fontSize:       14,
                                                                                                                                                                                                                                  fontWeight:     700,
                                                                                                                                                                                                                                                  color:          ap.status === 'approved' ? '#00C37B' : ap.status === 'rejected' ? '#E84545' : isActive ? '#F5A623' : '#6B7A99',
                                                                                                                                                                                                                                                                  background:     ap.status === 'approved' ? '#00C37B22' : ap.status === 'rejected' ? '#E8454522' : '#111827',
                                                                                                                                                                                                                                                                                  flexShrink:     0,
                                                                                                                                                                                                                                                                                                }}>
                                                                                                                                                                                                                                                                                                                {statusIcon(ap.status)}
                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                            {i < approvals.length - 1 && (
                                                                                                                                                                                                                                                                                                                                                            <div style={{
                                                                                                                                                                                                                                                                                                                                                                              width:      2,
                                                                                                                                                                                                                                                                                                                                                                                                height:     32,
                                                                                                                                                                                                                                                                                                                                                                                                                  background: ap.status === 'approved' ? '#00C37B' : '#1E2D45',
                                                                                                                                                                                                                                                                                                                                                                                                                                    margin:     '3px 0',
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ paddingBottom: 16, flex: 1 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ fontSize: 13, fontWeight: 600 }}>{ap.role?.toUpperCase()}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ fontSize: 11, color: '#6B7A99' }}>{ap.approver_name || ap.name}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {ap.decided_at && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ fontSize: 11, color: '#6B7A99' }}>{ap.decided_at}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {ap.comment && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize:     12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color:        ap.status === 'rejected' ? '#E84545' : '#E8EDF5',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      background:   '#111827',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding:      '4px 8px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginTop:    4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontStyle:    'italic',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "{ap.comment}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {isActive && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span style={{ fontSize: 10, color: '#F5A623', fontWeight: 700 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ● AWAITING ACTION
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
