export const theme = {
      bg:        '#0B0F1A',
        panel:     '#111827',
          card:      '#1A2235',
            border:    '#1E2D45',
              accent:    '#00C37B',
                accentDim: '#00C37B22',
                  gold:      '#F5A623',
                    goldDim:   '#F5A62322',
                      red:       '#E84545',
                        redDim:    '#E8454522',
                          blue:      '#3B82F6',
                            blueDim:   '#3B82F622',
                              purple:    '#A855F7',
                                purpleDim: '#A855F722',
                                  text:      '#E8EDF5',
                                    muted:     '#6B7A99',
                                    };
