import { NavLink, useNavigate } from 'react-router-dom';
import { useAuthStore } from '../../store/authStore';
import { NAV_BY_ROLE, ROLE_LABELS } from '../../utils/roleHelpers';
import Avatar from '../ui/Avatar';

export default function Sidebar() {
  const { user, logout } = useAuthStore();
    const navigate         = useNavigate();
      const nav              = NAV_BY_ROLE[user?.role] || [];

        const handleLogout = () => {
            logout();
                navigate('/login');
                  };

                    return (
                        <aside style={{
                              width:        240,
                                    background:   '#111827',
                                          borderRight:  '1px solid #1E2D45',
                                                display:      'flex',
                                                      flexDirection:'column',
                                                            height:       '100vh',
                                                                  position:     'sticky',
                                                                        top:          0,
                                                                              flexShrink:   0,
                                                                                  }}>
                                                                                        {/* Logo */}
                                                                                              <div style={{ padding: '22px 20px', borderBottom: '1px solid #1E2D45', display: 'flex', gap: 10, alignItems: 'center' }}>
                                                                                                      <div style={{
                                                                                                                width:          38,
                                                                                                                          height:         38,
                                                                                                                                    background:     '#00C37B',
                                                                                                                                              borderRadius:   10,
                                                                                                                                                        display:        'flex',
                                                                                                                                                                  alignItems:     'center',
                                                                                                                                                                            justifyContent: 'center',
                                                                                                                                                                                      fontWeight:     800,
                                                                                                                                                                                                color:          '#000',
                                                                                                                                                                                                          fontSize:       20,
                                                                                                                                                                                                                    flexShrink:     0,
                                                                                                                                                                                                                            }}>
                                                                                                                                                                                                                                      K
                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                <div style={{ fontSize: 12, fontWeight: 700, color: '#E8EDF5', lineHeight: 1.3 }}>KSU Procurement</div>
                                                                                                                                                                                                                                                                          <div style={{ fontSize: 10, color: '#6B7A99' }}>Kaduna State University</div>
                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                              {/* Nav links */}
                                                                                                                                                                                                                                                                                                    <nav style={{ flex: 1, padding: '14px 10px', overflowY: 'auto' }}>
                                                                                                                                                                                                                                                                                                            {nav.map((item) => (
                                                                                                                                                                                                                                                                                                                      <NavLink
                                                                                                                                                                                                                                                                                                                                  key={item.to}
                                                                                                                                                                                                                                                                                                                                              to={item.to}
                                                                                                                                                                                                                                                                                                                                                          end={item.to === '/'}
                                                                                                                                                                                                                                                                                                                                                                      style={({ isActive }) => ({
                                                                                                                                                                                                                                                                                                                                                                                    display:        'flex',
                                                                                                                                                                                                                                                                                                                                                                                                  alignItems:     'center',
                                                                                                                                                                                                                                                                                                                                                                                                                gap:            10,
                                                                                                                                                                                                                                                                                                                                                                                                                              padding:        '9px 12px',
                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius:   8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          marginBottom:   2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        textDecoration: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontWeight:     isActive ? 600 : 400,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize:       13,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color:          isActive ? '#00C37B' : '#6B7A99',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                background:     isActive ? '#00C37B22' : 'transparent',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              transition:     'all .15s',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span style={{ fontSize: 16 }}>{item.icon}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {item.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </NavLink>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </nav>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* User info */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ padding: '14px 16px', borderTop: '1px solid #1E2D45' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 10 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Avatar name={user?.name} size={34} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ minWidth: 0 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ fontSize: 12, fontWeight: 600, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', color: '#E8EDF5' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {user?.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ fontSize: 10, color: '#00C37B', textTransform: 'capitalize' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {ROLE_LABELS[user?.role]}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={handleLogout}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width:        '100%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background:   'transparent',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border:       '1px solid #1E2D45',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding:      '7px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color:        '#6B7A99',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          cursor:       'pointer',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize:     12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontFamily:   'Sora, sans-serif',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              transition:   'all .15s',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onMouseEnter={(e) => { e.currentTarget.style.borderColor = '#E84545'; e.currentTarget.style.color = '#E84545'; }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onMouseLeave={(e) => { e.currentTarget.style.borderColor = '#1E2D45'; e.currentTarget.style.color = '#6B7A99'; }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Sign Out
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </aside>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }