import styles from './Table.module.css';
import Spinner from '../Spinner/Spinner';

export default function Table({
  columns,
    data,
      onRowClick,
        loading,
          emptyMessage = 'No records found',
            emptyIcon    = 'bi-inbox',
            }) {
              if (loading) {
                  return (
                        <div className={styles.loadingBox}>
                                <Spinner />
                                        <span style={{ color: 'var(--muted)', fontSize: 13 }}>Loading...</span>
                                              </div>
                                                  );
                                                    }

                                                      return (
                                                          <div className={styles.wrapper}>
                                                                <table className={styles.table}>
                                                                        <thead>
                                                                                  <tr>
                                                                                              {columns.map((col) => (
                                                                                                            <th
                                                                                                                            key={col.key}
                                                                                                                                            className={styles.th}
                                                                                                                                                            style={{ textAlign: col.align || 'left', width: col.width }}
                                                                                                                                                                          >
                                                                                                                                                                                          {col.label}
                                                                                                                                                                                                        </th>
                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                              </tr>
                                                                                                                                                                                                                                      </thead>
                                                                                                                                                                                                                                              <tbody>
                                                                                                                                                                                                                                                        {data.length === 0 ? (
                                                                                                                                                                                                                                                                    <tr>
                                                                                                                                                                                                                                                                                  <td colSpan={columns.length} className={styles.empty}>
                                                                                                                                                                                                                                                                                                  <i className={`bi ${emptyIcon}`} style={{ fontSize: 32, color: 'var(--muted)' }} />
                                                                                                                                                                                                                                                                                                                  <div>{emptyMessage}</div>
                                                                                                                                                                                                                                                                                                                                </td>
                                                                                                                                                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                  data.map((row, i) => (
                                                                                                                                                                                                                                                                                                                                                                                <tr
                                                                                                                                                                                                                                                                                                                                                                                                key={row._id || row.id || i}
                                                                                                                                                                                                                                                                                                                                                                                                                className={[styles.tr, onRowClick ? styles.clickable : ''].join(' ')}
                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => onRowClick?.(row)}
                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                              {columns.map((col) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <td
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={col.key}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className={styles.td}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{ textAlign: col.align || 'left' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {col.render
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ? col.render(row[col.key], row)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              : row[col.key] ?? '—'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }