import { requireAuth }    from '@/lib/auth';
import { getSummary, getByDepartment, getMonthly } from '@/services/report.service';

export async function GET(request) {
  try {
      requireAuth(request);

          const { searchParams } = new URL(request.url);
              const year = searchParams.get('year');

                  // Dynamically import PDFKit (server only)
                      const PDFDocument = (await import('pdfkit')).default;
                          const doc         = new PDFDocument({ margin: 50, size: 'A4' });

                              // Gather report data
                                  const [summary, byDept, monthly] = await Promise.all([
                                        getSummary(year),
                                              getByDepartment(year),
                                                    getMonthly(year),
                                                        ]);

                                                            // ── Cover Header ───────────────────────────────────────────
                                                                doc.fontSize(18)
                                                                       .font('Helvetica-Bold')
                                                                              .text('KADUNA STATE UNIVERSITY', { align: 'center' });

                                                                                  doc.fontSize(11)
                                                                                         .font('Helvetica')
                                                                                                .text('Procurement Requisition System', { align: 'center' });

                                                                                                    doc.moveDown(0.5);
                                                                                                        doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
                                                                                                            doc.moveDown();

                                                                                                                doc.fontSize(14)
                                                                                                                       .font('Helvetica-Bold')
                                                                                                                              .text(`PROCUREMENT SUMMARY REPORT — FY ${summary.fiscalYear}`, { align: 'center' });

                                                                                                                                  doc.fontSize(10)
                                                                                                                                         .font('Helvetica')
                                                                                                                                                .text(`Generated: ${new Date().toLocaleDateString('en-NG')}`, { align: 'center' });

                                                                                                                                                    doc.moveDown(1.5);

                                                                                                                                                        // ── Section 1: Summary Statistics ─────────────────────────
                                                                                                                                                            doc.fontSize(12)
                                                                                                                                                                   .font('Helvetica-Bold')
                                                                                                                                                                          .text('1. SUMMARY STATISTICS');

                                                                                                                                                                              doc.moveDown(0.5);
                                                                                                                                                                                  doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
                                                                                                                                                                                      doc.moveDown(0.5);

                                                                                                                                                                                          const stats = [
                                                                                                                                                                                                ['Total Requisitions',      summary.total],
                                                                                                                                                                                                      ['Approved',                summary.approved],
                                                                                                                                                                                                            ['Pending Review',          summary.pending],
                                                                                                                                                                                                                  ['Rejected',                summary.rejected],
                                                                                                                                                                                                                        ['Total Approved Value',    `₦${Number(summary.totalValue).toLocaleString('en-NG')}`],
                                                                                                                                                                                                                            ];

                                                                                                                                                                                                                                doc.font('Helvetica').fontSize(10);
                                                                                                                                                                                                                                    stats.forEach(([label, value]) => {
                                                                                                                                                                                                                                          doc.text(`${label}:`, 60, doc.y, { continued: true, width: 200 });
                                                                                                                                                                                                                                                doc.text(`${value}`,  { align: 'left' });
                                                                                                                                                                                                                                                      doc.moveDown(0.4);
                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                              doc.moveDown(1);

                                                                                                                                                                                                                                                                  // ── Section 2: Department Breakdown ───────────────────────
                                                                                                                                                                                                                                                                      doc.fontSize(12)
                                                                                                                                                                                                                                                                             .font('Helvetica-Bold')
                                                                                                                                                                                                                                                                                    .text('2. SPEND BY DEPARTMENT');

                                                                                                                                                                                                                                                                                        doc.moveDown(0.5);
                                                                                                                                                                                                                                                                                            doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
                                                                                                                                                                                                                                                                                                doc.moveDown(0.5);

                                                                                                                                                                                                                                                                                                    // Table header
                                                                                                                                                                                                                                                                                                        doc.font('Helvetica-Bold').fontSize(9);
                                                                                                                                                                                                                                                                                                            const dCol = [50, 230, 340, 420, 480];
                                                                                                                                                                                                                                                                                                                const dHdr = ['Department', 'Total Value (₦)', 'Count', 'Approved', '%'];
                                                                                                                                                                                                                                                                                                                    dHdr.forEach((h, i) => doc.text(h, dCol[i], doc.y, { width: 100 }));
                                                                                                                                                                                                                                                                                                                        doc.moveDown(0.5);
                                                                                                                                                                                                                                                                                                                            doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
                                                                                                                                                                                                                                                                                                                                doc.moveDown(0.3);

                                                                                                                                                                                                                                                                                                                                    doc.font('Helvetica').fontSize(9);
                                                                                                                                                                                                                                                                                                                                        byDept.forEach((d) => {
                                                                                                                                                                                                                                                                                                                                              const rowY = doc.y;
                                                                                                                                                                                                                                                                                                                                                    const vals = [
                                                                                                                                                                                                                                                                                                                                                            d.department?.name || '—',
                                                                                                                                                                                                                                                                                                                                                                    Number(d.total).toLocaleString('en-NG'),
                                                                                                                                                                                                                                                                                                                                                                            `${d.count}`,
                                                                                                                                                                                                                                                                                                                                                                                    `${d.approved}`,
                                                                                                                                                                                                                                                                                                                                                                                            `${d.count ? Math.round((d.approved / d.count) * 100) : 0}%`,
                                                                                                                                                                                                                                                                                                                                                                                                  ];
                                                                                                                                                                                                                                                                                                                                                                                                        vals.forEach((v, i) => doc.text(v, dCol[i], rowY, { width: 160 }));
                                                                                                                                                                                                                                                                                                                                                                                                              doc.moveDown(0.7);
                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                      doc.moveDown(1);

                                                                                                                                                                                                                                                                                                                                                                                                                          // ── Section 3: Monthly Trend ───────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                              doc.fontSize(12)
                                                                                                                                                                                                                                                                                                                                                                                                                                     .font('Helvetica-Bold')
                                                                                                                                                                                                                                                                                                                                                                                                                                            .text('3. MONTHLY REQUISITION TREND');

                                                                                                                                                                                                                                                                                                                                                                                                                                                doc.moveDown(0.5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
                                                                                                                                                                                                                                                                                                                                                                                                                                                        doc.moveDown(0.5);

                                                                                                                                                                                                                                                                                                                                                                                                                                                            const monthNames = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                doc.font('Helvetica-Bold').fontSize(9);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const mCol = [50, 200, 320, 440];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ['Month', 'Requisitions', 'Total Value (₦)', 'Avg Value (₦)'].forEach(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (h, i) => doc.text(h, mCol[i], doc.y, { width: 140 })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      doc.moveDown(0.5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              doc.moveDown(0.3);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  doc.font('Helvetica').fontSize(9);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      monthly.forEach((m) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const rowY  = doc.y;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const avg   = m.count ? Math.round(m.value / m.count) : 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const vals  = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                monthNames[(m._id || 1) - 1],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        `${m.count}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Number(m.value).toLocaleString('en-NG'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Number(avg).toLocaleString('en-NG'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    vals.forEach((v, i) => doc.text(v, mCol[i], rowY, { width: 140 }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          doc.moveDown(0.7);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // ── Footer ────────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      doc.moveDown(2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              doc.moveDown(0.5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  doc.fontSize(9)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         .font('Helvetica')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .fillColor('#999')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       .text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `This report was generated automatically by the KSU Procurement System on ${new Date().toLocaleString('en-NG')}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         { align: 'center' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    doc.end();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Collect PDF buffer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const chunks = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await new Promise((resolve, reject) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      doc.on('data',  (chunk) => chunks.push(chunk));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            doc.on('end',   resolve);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  doc.on('error', reject);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const buffer = Buffer.concat(chunks);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return new Response(buffer, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Content-Type':        'application/pdf',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'Content-Disposition': `attachment; filename="KSU-Procurement-Report-${summary.fiscalYear}.pdf"`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          JSON.stringify({ success: false, message: err.message }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { status: 500, headers: { 'Content-Type': 'application/json' } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }