export default function StatCard({ label, value, sub, accent, icon }) {
      return (
          <div style={{
                background:   '#1A2235',
                      border:       '1px solid #1E2D45',
                            borderRadius: 14,
                                  padding:      24,
                                      }}>
                                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                                                    <div>
                                                              <div style={{
                                                                          fontSize:      12,
                                                                                      color:         '#6B7A99',
                                                                                                  fontWeight:    600,
                                                                                                              textTransform: 'uppercase',
                                                                                                                          letterSpacing: .5,
                                                                                                                                      marginBottom:  10,
                                                                                                                                                }}>
                                                                                                                                                            {label}
                                                                                                                                                                      </div>
                                                                                                                                                                                <div style={{
                                                                                                                                                                                            fontSize:    28,
                                                                                                                                                                                                        fontWeight:  700,
                                                                                                                                                                                                                    color:       accent || '#E8EDF5',
                                                                                                                                                                                                                                letterSpacing: -1,
                                                                                                                                                                                                                                            lineHeight:  1,
                                                                                                                                                                                                                                                      }}>
                                                                                                                                                                                                                                                                  {value}
                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                      {sub && (
                                                                                                                                                                                                                                                                                                  <div style={{ fontSize: 12, color: '#6B7A99', marginTop: 6 }}>
                                                                                                                                                                                                                                                                                                                {sub}
                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                      {icon && (
                                                                                                                                                                                                                                                                                                                                                                <div style={{
                                                                                                                                                                                                                                                                                                                                                                            fontSize:       22,
                                                                                                                                                                                                                                                                                                                                                                                        background:     '#111827',
                                                                                                                                                                                                                                                                                                                                                                                                    width:          44,
                                                                                                                                                                                                                                                                                                                                                                                                                height:         44,
                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius:   10,
                                                                                                                                                                                                                                                                                                                                                                                                                                        display:        'flex',
                                                                                                                                                                                                                                                                                                                                                                                                                                                    alignItems:     'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                justifyContent: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {icon}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
