export default function Table({ columns, data, onRowClick, emptyMessage = 'No records found' }) {
      return (
          <div style={{ background: '#1A2235', border: '1px solid #1E2D45', borderRadius: 14, overflow: 'hidden' }}>
                <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                        <thead>
                                  <tr style={{ background: '#111827' }}>
                                              {columns.map((col) => (
                                                            <th key={col.key} style={{
                                                                            padding:       '12px 16px',
                                                                                            textAlign:     col.align || 'left',
                                                                                                            fontSize:      11,
                                                                                                                            color:         '#6B7A99',
                                                                                                                                            fontWeight:    600,
                                                                                                                                                            textTransform: 'uppercase',
                                                                                                                                                                            letterSpacing: .5,
                                                                                                                                                                                            whiteSpace:    'nowrap',
                                                                                                                                                                                                          }}>
                                                                                                                                                                                                                          {col.label}
                                                                                                                                                                                                                                        </th>
                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                              </tr>
                                                                                                                                                                                                                                                                      </thead>
                                                                                                                                                                                                                                                                              <tbody>
                                                                                                                                                                                                                                                                                        {data.length === 0 ? (
                                                                                                                                                                                                                                                                                                    <tr>
                                                                                                                                                                                                                                                                                                                  <td colSpan={columns.length} style={{ textAlign: 'center', padding: 48, color: '#6B7A99' }}>
                                                                                                                                                                                                                                                                                                                                  {emptyMessage}
                                                                                                                                                                                                                                                                                                                                                </td>
                                                                                                                                                                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                  data.map((row, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                <tr
                                                                                                                                                                                                                                                                                                                                                                                                                key={row.id || i}
                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => onRowClick?.(row)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderTop:  '1px solid #1E2D45',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cursor:     onRowClick ? 'pointer' : 'default',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      transition: 'background .15s',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onMouseEnter={(e) => { if (onRowClick) e.currentTarget.style.background = '#1E2D4544'; }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onMouseLeave={(e) => { e.currentTarget.style.background = 'transparent'; }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {columns.map((col) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td key={col.key} style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding:   '13px 16px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize:  13,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  textAlign: col.align || 'left',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color:     col.color || '#E8EDF5',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ...col.style,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {col.render ? col.render(row[col.key], row) : row[col.key]}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
