import { Routes, Route, Navigate } from 'react-router-dom';
import { Toaster } from 'react-hot-toast';
import { useAuthStore } from './store/authStore';

// Layout
import PageWrapper from './components/layout/PageWrapper';

// Pages
import Login             from './pages/Login';
import Dashboard         from './pages/Dashboard';
import RequisitionList   from './pages/requisitions/RequisitionList';
import RequisitionDetail from './pages/requisitions/RequisitionDetail';
import NewRequisitionForm from './pages/requisitions/NewRequisitionForm';
import ApprovalsQueue    from './pages/approvals/ApprovalsQueue';
import VendorList        from './pages/vendors/VendorList';
import VendorForm        from './pages/vendors/VendorForm';
import LPOList           from './pages/lpo/LPOList';
import LPODocument       from './pages/lpo/LPODocument';
import BudgetTracker     from './pages/budget/BudgetTracker';
import Reports           from './pages/reports/Reports';
import AuditTrail        from './pages/audit/AuditTrail';
import Settings          from './pages/settings/Settings';

// Protected route wrapper
const PrivateRoute = ({ children }) => {
  const token = useAuthStore((s) => s.token);
    return token ? children : <Navigate to="/login" replace />;
    };

    // Role protected route
    const RoleRoute = ({ children, roles }) => {
      const user = useAuthStore((s) => s.user);
        if (!user) return <Navigate to="/login" replace />;
          if (!roles.includes(user.role)) return <Navigate to="/" replace />;
            return children;
            };

            export default function App() {
              return (
                  <>
                        <Toaster
                                position="top-right"
                                        toastOptions={{
                                                  duration: 4000,
                                                            style: {
                                                                        background: '#1A2235',
                                                                                    color:      '#E8EDF5',
                                                                                                border:     '1px solid #1E2D45',
                                                                                                            fontFamily: 'Sora, sans-serif',
                                                                                                                        fontSize:   '13px',
                                                                                                                                  },
                                                                                                                                            success: { iconTheme: { primary: '#00C37B', secondary: '#000' } },
                                                                                                                                                      error:   { iconTheme: { primary: '#E84545', secondary: '#fff' } },
                                                                                                                                                              }}
                                                                                                                                                                    />

                                                                                                                                                                          <Routes>
                                                                                                                                                                                  {/* Public */}
                                                                                                                                                                                          <Route path="/login" element={<Login />} />

                                                                                                                                                                                                  {/* Protected */}
                                                                                                                                                                                                          <Route
                                                                                                                                                                                                                    path="/"
                                                                                                                                                                                                                              element={
                                                                                                                                                                                                                                          <PrivateRoute>
                                                                                                                                                                                                                                                        <PageWrapper />
                                                                                                                                                                                                                                                                    </PrivateRoute>
                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                <Route index                   element={<Dashboard />} />
                                                                                                                                                                                                                                                                                                          <Route path="requisitions"     element={<RequisitionList />} />
                                                                                                                                                                                                                                                                                                                    <Route path="requisitions/new" element={<NewRequisitionForm />} />
                                                                                                                                                                                                                                                                                                                              <Route path="requisitions/:id" element={<RequisitionDetail />} />

                                                                                                                                                                                                                                                                                                                                        <Route path="approvals" element={
                                                                                                                                                                                                                                                                                                                                                    <RoleRoute roles={['hod','procurement','finance','vc','admin']}>
                                                                                                                                                                                                                                                                                                                                                                  <ApprovalsQueue />
                                                                                                                                                                                                                                                                                                                                                                              </RoleRoute>
                                                                                                                                                                                                                                                                                                                                                                                        } />

                                                                                                                                                                                                                                                                                                                                                                                                  <Route path="vendors"     element={<VendorList />} />
                                                                                                                                                                                                                                                                                                                                                                                                            <Route path="vendors/new" element={
                                                                                                                                                                                                                                                                                                                                                                                                                        <RoleRoute roles={['procurement','admin']}>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <VendorForm />
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </RoleRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            } />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Route path="lpo"     element={<LPOList />} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Route path="lpo/:id" element={<LPODocument />} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Route path="budget" element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <RoleRoute roles={['finance','vc','admin']}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <BudgetTracker />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </RoleRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Route path="reports" element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <RoleRoute roles={['procurement','finance','vc','admin']}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Reports />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </RoleRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Route path="audit" element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <RoleRoute roles={['admin','procurement','finance','vc']}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <AuditTrail />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </RoleRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Route path="settings" element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <RoleRoute roles={['admin']}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Settings />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </RoleRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Route>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Catch all */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Route path="*" element={<Navigate to="/" replace />} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Routes>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }